name: GymWebService
services:
  api:
    image: gymwebservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStringPostgres=Host=postgres;Port=5433;Database=GymWebService;Username=pgadmin;Password=pgadmin
      - JWT_Issuer=
      - JWT_Audience=
      - JWT_Key=key
      - FRONTEND_URL=
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=GymWebService
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - PGPORT=5433
    ports:
      - 5434:5433
    volumes:
      - ../sql_init:/docker-entrypoint-initdb.d
      - ../postgres/data:/var/lib/postgresql/data
